// Package config renders the dynamic edge Caddyfile (customer site blocks) from
// the control-plane's source of truth and publishes new versions to edges.
package config

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/aegis/control-plane/internal/appcfg"
	"github.com/aegis/control-plane/internal/dns"
	"github.com/aegis/control-plane/internal/store"
)

// RedisChannel is the pub/sub channel edges subscribe to for config-change pokes.
const RedisChannel = "edge:config"

// Renderer turns DB state into a Caddyfile and versions it.
type Renderer struct {
	Store *store.Store
	Cfg   *appcfg.Config
}

func New(st *store.Store, cfg *appcfg.Config) *Renderer {
	return &Renderer{Store: st, Cfg: cfg}
}

var nonAlnum = regexp.MustCompile(`[^a-zA-Z0-9]+`)

func zoneName(host string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(host, "_"), "_")
}

// originURL normalises a proxied record's content into an upstream URL.
func originURL(content string) string {
	content = strings.TrimSpace(content)
	if strings.HasPrefix(content, "http://") || strings.HasPrefix(content, "https://") {
		return content
	}
	return "http://" + content
}

// Render produces the dynamic Caddyfile (customer site blocks only). Global
// options + the control-plane site live in the image's base Caddyfile.
func (r *Renderer) Render(ctx context.Context) (string, error) {
	domains, err := r.Store.ListActiveDomainsForRender(ctx)
	if err != nil {
		return "", err
	}

	// Global threat-feed blocklist (Spamhaus DROP, FireHOL, …). Rendered once as
	// a reusable snippet and imported into every proxied site, so thousands of
	// CIDRs are not duplicated per-host.
	feedCIDRs, err := r.Store.ListEnabledThreatFeedCIDRs(ctx)
	if err != nil {
		return "", err
	}
	snippet, hasFeeds := threatFeedSnippet(feedCIDRs)

	var b strings.Builder
	b.WriteString("# Generated by Aegis control-plane. Do not edit by hand.\n\n")
	if hasFeeds {
		b.WriteString(snippet)
	}

	for _, d := range domains {
		recs, err := r.Store.ListProxiedRecords(ctx, d.ID)
		if err != nil {
			return "", err
		}
		if len(recs) == 0 {
			continue
		}
		policy, err := r.Store.GetOrCreatePolicy(ctx, d.ID)
		if err != nil {
			return "", err
		}
		blocks, err := r.Store.ListBlocklistsForDomain(ctx, d.ID)
		if err != nil {
			return "", err
		}
		var overrides []store.WAFRouteOverride
		if policy.WAFEnabled {
			if overrides, err = r.Store.ListWAFOverridesForRender(ctx, d.ID); err != nil {
				return "", err
			}
		}

		// Group proxied origins by hostname (multiple origins => LB pool).
		pools := map[string][]string{}
		var hosts []string
		for _, rec := range recs {
			host := dns.FQDN(d.Name, rec.Name)
			if _, ok := pools[host]; !ok {
				hosts = append(hosts, host)
			}
			pools[host] = append(pools[host], originURL(rec.Content))
		}
		sort.Strings(hosts)
		for _, host := range hosts {
			r.writeSite(&b, host, policy, pools[host], blocks, hasFeeds, overrides)
		}
	}
	return b.String(), nil
}

// threatFeedSnippet renders a reusable Caddyfile snippet that hard-403s any
// client whose source IP falls in one of the supplied (pre-validated, sorted)
// CIDRs. Returns ("", false) when there is nothing to block. The snippet is
// imported per-site via `import aegis_threatfeeds`.
func threatFeedSnippet(cidrs []string) (string, bool) {
	if len(cidrs) == 0 {
		return "", false
	}
	var b strings.Builder
	b.WriteString("(aegis_threatfeeds) {\n")
	fmt.Fprintf(&b, "\t@aegis_threatfeed remote_ip %s\n", strings.Join(cidrs, " "))
	b.WriteString("\trespond @aegis_threatfeed \"Forbidden\" 403\n")
	b.WriteString("}\n\n")
	return b.String(), true
}

func (r *Renderer) writeSite(b *strings.Builder, host string, p *store.SecurityPolicy, origins []string, blocks []store.Blocklist, importFeeds bool, wafOverrides []store.WAFRouteOverride) {
	fmt.Fprintf(b, "%s {\n", host)

	if r.Cfg.EdgeTLSMode == "internal" {
		b.WriteString("\ttls internal\n")
	}
	if !p.HTTPSRedirect {
		b.WriteString("\t# https redirect disabled by policy (auto_https off would be global)\n")
	}

	// Global threat-feed blocklist (shared snippet defined once at the top).
	if importFeeds {
		b.WriteString("\timport aegis_threatfeeds\n")
	}

	// IP/CIDR blocklist -> hard 403 (kind=ip|cidr, action=block).
	var ipRanges []string
	for _, bl := range blocks {
		if (bl.Kind == "ip" || bl.Kind == "cidr") && bl.Action == "block" {
			ipRanges = append(ipRanges, bl.Value)
		}
	}
	if len(ipRanges) > 0 {
		fmt.Fprintf(b, "\t@blocked remote_ip %s\n\trespond @blocked \"Forbidden\" 403\n", strings.Join(ipRanges, " "))
	}

	// TLS/HTTP fingerprint (sets vars consumed by botscore).
	b.WriteString("\tja4\n")

	// Rate limiting.
	if p.RateLimitEnabled {
		zn := zoneName(host)
		fmt.Fprintf(b, "\trate_limit {\n\t\tzone %s {\n\t\t\tkey {http.request.remote_ip}\n\t\t\tevents %d\n\t\t\twindow 1m\n\t\t}\n\t}\n",
			zn, p.RateLimitRPM)
	}

	// Behavioural bot scoring + challenge.
	if p.BotProtection != "off" {
		b.WriteString("\tbotscore {\n")
		fmt.Fprintf(b, "\t\tsensitivity %s\n", p.BotProtection)
		if p.BotAllowVerified {
			b.WriteString("\t\tallow_verified_bots\n")
		}
		b.WriteString("\t}\n")
		if p.ChallengeEnabled {
			b.WriteString("\tchallenge {\n\t\tsecret {env.CHALLENGE_SECRET}\n")
			if p.ChallengeMode == "captcha" && p.CaptchaProvider != "" && p.CaptchaSitekey != "" && p.CaptchaSecret != "" {
				fmt.Fprintf(b, "\t\tmode captcha\n\t\tprovider %s\n\t\tsitekey %s\n\t\tcaptcha_secret %s\n",
					p.CaptchaProvider, p.CaptchaSitekey, p.CaptchaSecret)
			}
			b.WriteString("\t}\n")
		}
	}

	// WAF (Coraza + OWASP CRS, baked into the image at /etc/caddy/coraza).
	if p.WAFEnabled {
		fmt.Fprintf(b, "\tcoraza_waf {\n\t\tdirectives `\n%s\t\t`\n\t}\n", corazaDirectives(p, wafOverrides))
	}

	// Edge cache (Souin/cache-handler, Redis-backed; global block in base).
	if p.CacheEnabled {
		fmt.Fprintf(b, "\tcache {\n\t\tttl %ds\n\t}\n", p.CacheTTL)
	}

	// Reverse proxy to origin pool.
	fmt.Fprintf(b, "\treverse_proxy %s {\n\t\tlb_policy round_robin\n\t\tlb_try_duration 5s\n\t\thealth_uri /\n\t\thealth_interval 15s\n\t}\n", strings.Join(origins, " "))

	b.WriteString("}\n\n")
}

// wafOverrideBaseID is the first id assigned to generated per-route override
// rules. It sits above the OWASP CRS range (900000–999999) to avoid collisions.
const wafOverrideBaseID = 9010000

// corazaDirectives builds the inner SecLang for a domain's coraza_waf block:
// the CRS includes, per-route override rules (phase 1, before CRS evaluates),
// the operator's validated custom rules (after CRS), and the engine mode.
// overrides must already be filtered to enabled and ordered for determinism.
func corazaDirectives(p *store.SecurityPolicy, overrides []store.WAFRouteOverride) string {
	engine := "On"
	if p.WAFMode == "detect" {
		engine = "DetectionOnly"
	}
	var b strings.Builder
	w := func(s string) { b.WriteString("\t\t\t"); b.WriteString(s); b.WriteByte('\n') }

	w("Include /etc/caddy/coraza/coraza.conf")
	w("Include /etc/caddy/coraza/crs-setup.conf")
	fmt.Fprintf(&b, "\t\t\tSecAction \"id:900110,phase:1,pass,nolog,setvar:tx.blocking_paranoia_level=%d\"\n", p.WAFParanoia)

	id := wafOverrideBaseID
	for _, o := range overrides {
		if rule, ok := wafOverrideRule(id, o); ok {
			w(rule)
			id++
		}
	}

	w("Include /etc/caddy/coraza/rules/*.conf")

	if cr := strings.TrimSpace(p.WAFCustomRules); cr != "" {
		for _, line := range strings.Split(cr, "\n") {
			if t := strings.TrimSpace(strings.TrimRight(line, "\r")); t != "" {
				w(t)
			}
		}
	}

	w("SecRuleEngine " + engine)
	return b.String()
}

// wafOverrideRule renders one per-route override as a path-scoped SecRule. It
// returns (rule, false) when the override is a no-op (mode inherit, no excluded
// rules, no paranoia override).
func wafOverrideRule(id int, o store.WAFRouteOverride) (string, bool) {
	var actions []string
	switch o.Mode {
	case "off":
		actions = append(actions, "ctl:ruleEngine=Off")
	case "detect":
		actions = append(actions, "ctl:ruleEngine=DetectionOnly")
	}
	for _, rid := range parseRuleIDs(o.ExcludedRules) {
		actions = append(actions, "ctl:ruleRemoveById="+rid)
	}
	if o.Paranoia != nil {
		actions = append(actions,
			fmt.Sprintf("setvar:tx.blocking_paranoia_level=%d", *o.Paranoia),
			fmt.Sprintf("setvar:tx.detection_paranoia_level=%d", *o.Paranoia))
	}
	if len(actions) == 0 {
		return "", false
	}
	return fmt.Sprintf(`SecRule REQUEST_URI "@beginsWith %s" "id:%d,phase:1,pass,nolog,t:none,%s"`,
		sanitizeWAFPath(o.Path), id, strings.Join(actions, ",")), true
}

// parseRuleIDs extracts the numeric CRS rule IDs from a free-form list
// (space/comma separated). Non-numeric tokens are dropped.
func parseRuleIDs(s string) []string {
	var out []string
	for _, tok := range strings.FieldsFunc(s, func(r rune) bool { return r == ' ' || r == ',' || r == '\t' }) {
		if tok != "" && strings.IndexFunc(tok, func(r rune) bool { return r < '0' || r > '9' }) == -1 {
			out = append(out, tok)
		}
	}
	return out
}

// sanitizeWAFPath strips characters that would break out of the SecRule's quoted
// operator argument (defence in depth; the API also validates on write).
func sanitizeWAFPath(p string) string {
	return strings.NewReplacer("\"", "", "`", "", "\n", "", "\r", "").Replace(p)
}

// Rebuild renders the current config, and if it changed from the latest stored
// bundle, persists a new version and pokes edges via Redis. Returns the active
// version and whether it changed.
func (r *Renderer) Rebuild(ctx context.Context) (int64, bool, error) {
	rendered, err := r.Render(ctx)
	if err != nil {
		return 0, false, err
	}
	sum := checksum(rendered)
	prev, err := r.Store.LatestChecksum(ctx)
	if err != nil {
		return 0, false, err
	}
	if prev == sum {
		b, err := r.Store.GetLatestBundle(ctx)
		if err != nil {
			return 0, false, nil
		}
		return b.Version, false, nil
	}
	version, err := r.Store.InsertConfigBundle(ctx, rendered, sum)
	if err != nil {
		return 0, false, err
	}
	// Best-effort poke; agents also long-poll so a missed publish self-heals.
	_ = r.Store.Redis.Publish(ctx, RedisChannel, fmt.Sprintf("%d", version)).Err()
	return version, true, nil
}

func checksum(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}
