// Package config renders the dynamic edge Caddyfile (customer site blocks) from
// the control-plane's source of truth and publishes new versions to edges.
package config

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/aegis/control-plane/internal/appcfg"
	"github.com/aegis/control-plane/internal/dns"
	"github.com/aegis/control-plane/internal/store"
)

// RedisChannel is the pub/sub channel edges subscribe to for config-change pokes.
const RedisChannel = "edge:config"

// Renderer turns DB state into a Caddyfile and versions it.
type Renderer struct {
	Store *store.Store
	Cfg   *appcfg.Config
}

func New(st *store.Store, cfg *appcfg.Config) *Renderer {
	return &Renderer{Store: st, Cfg: cfg}
}

var nonAlnum = regexp.MustCompile(`[^a-zA-Z0-9]+`)

func zoneName(host string) string {
	return strings.Trim(nonAlnum.ReplaceAllString(host, "_"), "_")
}

// originURL normalises a proxied record's content into an upstream URL.
func originURL(content string) string {
	content = strings.TrimSpace(content)
	if strings.HasPrefix(content, "http://") || strings.HasPrefix(content, "https://") {
		return content
	}
	return "http://" + content
}

// Render produces the dynamic Caddyfile (customer site blocks only). Global
// options + the control-plane site live in the image's base Caddyfile.
func (r *Renderer) Render(ctx context.Context) (string, error) {
	domains, err := r.Store.ListActiveDomainsForRender(ctx)
	if err != nil {
		return "", err
	}

	// Global threat-feed blocklist (Spamhaus DROP, FireHOL, …). Rendered once as
	// a reusable snippet and imported into every proxied site, so thousands of
	// CIDRs are not duplicated per-host.
	feedCIDRs, err := r.Store.ListEnabledThreatFeedCIDRs(ctx)
	if err != nil {
		return "", err
	}
	snippet, hasFeeds := threatFeedSnippet(feedCIDRs)

	var b strings.Builder
	b.WriteString("# Generated by Aegis control-plane. Do not edit by hand.\n\n")
	if hasFeeds {
		b.WriteString(snippet)
	}

	for _, d := range domains {
		recs, err := r.Store.ListProxiedRecords(ctx, d.ID)
		if err != nil {
			return "", err
		}
		if len(recs) == 0 {
			continue
		}
		policy, err := r.Store.GetOrCreatePolicy(ctx, d.ID)
		if err != nil {
			return "", err
		}
		blocks, err := r.Store.ListBlocklistsForDomain(ctx, d.ID)
		if err != nil {
			return "", err
		}

		// Group proxied origins by hostname (multiple origins => LB pool).
		pools := map[string][]string{}
		var hosts []string
		for _, rec := range recs {
			host := dns.FQDN(d.Name, rec.Name)
			if _, ok := pools[host]; !ok {
				hosts = append(hosts, host)
			}
			pools[host] = append(pools[host], originURL(rec.Content))
		}
		sort.Strings(hosts)
		for _, host := range hosts {
			r.writeSite(&b, host, policy, pools[host], blocks, hasFeeds)
		}
	}
	return b.String(), nil
}

// threatFeedSnippet renders a reusable Caddyfile snippet that hard-403s any
// client whose source IP falls in one of the supplied (pre-validated, sorted)
// CIDRs. Returns ("", false) when there is nothing to block. The snippet is
// imported per-site via `import aegis_threatfeeds`.
func threatFeedSnippet(cidrs []string) (string, bool) {
	if len(cidrs) == 0 {
		return "", false
	}
	var b strings.Builder
	b.WriteString("(aegis_threatfeeds) {\n")
	fmt.Fprintf(&b, "\t@aegis_threatfeed remote_ip %s\n", strings.Join(cidrs, " "))
	b.WriteString("\trespond @aegis_threatfeed \"Forbidden\" 403\n")
	b.WriteString("}\n\n")
	return b.String(), true
}

func (r *Renderer) writeSite(b *strings.Builder, host string, p *store.SecurityPolicy, origins []string, blocks []store.Blocklist, importFeeds bool) {
	fmt.Fprintf(b, "%s {\n", host)

	if r.Cfg.EdgeTLSMode == "internal" {
		b.WriteString("\ttls internal\n")
	}
	if !p.HTTPSRedirect {
		b.WriteString("\t# https redirect disabled by policy (auto_https off would be global)\n")
	}

	// Global threat-feed blocklist (shared snippet defined once at the top).
	if importFeeds {
		b.WriteString("\timport aegis_threatfeeds\n")
	}

	// IP/CIDR blocklist -> hard 403 (kind=ip|cidr, action=block).
	var ipRanges []string
	for _, bl := range blocks {
		if (bl.Kind == "ip" || bl.Kind == "cidr") && bl.Action == "block" {
			ipRanges = append(ipRanges, bl.Value)
		}
	}
	if len(ipRanges) > 0 {
		fmt.Fprintf(b, "\t@blocked remote_ip %s\n\trespond @blocked \"Forbidden\" 403\n", strings.Join(ipRanges, " "))
	}

	// TLS/HTTP fingerprint (sets vars consumed by botscore).
	b.WriteString("\tja4\n")

	// Rate limiting.
	if p.RateLimitEnabled {
		zn := zoneName(host)
		fmt.Fprintf(b, "\trate_limit {\n\t\tzone %s {\n\t\t\tkey {http.request.remote_ip}\n\t\t\tevents %d\n\t\t\twindow 1m\n\t\t}\n\t}\n",
			zn, p.RateLimitRPM)
	}

	// Behavioural bot scoring + challenge.
	if p.BotProtection != "off" {
		fmt.Fprintf(b, "\tbotscore {\n\t\tsensitivity %s\n\t}\n", p.BotProtection)
		if p.ChallengeEnabled {
			fmt.Fprintf(b, "\tchallenge {\n\t\tsecret {env.CHALLENGE_SECRET}\n\t}\n")
		}
	}

	// WAF (Coraza + OWASP CRS, baked into the image at /etc/caddy/coraza).
	if p.WAFEnabled {
		engine := "On"
		if p.WAFMode == "detect" {
			engine = "DetectionOnly"
		}
		fmt.Fprintf(b, "\tcoraza_waf {\n\t\tdirectives `\n"+
			"\t\t\tInclude /etc/caddy/coraza/coraza.conf\n"+
			"\t\t\tInclude /etc/caddy/coraza/crs-setup.conf\n"+
			"\t\t\tSecAction \"id:900110,phase:1,pass,nolog,setvar:tx.blocking_paranoia_level=%d\"\n"+
			"\t\t\tInclude /etc/caddy/coraza/rules/*.conf\n"+
			"\t\t\tSecRuleEngine %s\n"+
			"\t\t`\n\t}\n", p.WAFParanoia, engine)
	}

	// Edge cache (Souin/cache-handler, Redis-backed; global block in base).
	if p.CacheEnabled {
		fmt.Fprintf(b, "\tcache {\n\t\tttl %ds\n\t}\n", p.CacheTTL)
	}

	// Reverse proxy to origin pool.
	fmt.Fprintf(b, "\treverse_proxy %s {\n\t\tlb_policy round_robin\n\t\tlb_try_duration 5s\n\t\thealth_uri /\n\t\thealth_interval 15s\n\t}\n", strings.Join(origins, " "))

	b.WriteString("}\n\n")
}

// Rebuild renders the current config, and if it changed from the latest stored
// bundle, persists a new version and pokes edges via Redis. Returns the active
// version and whether it changed.
func (r *Renderer) Rebuild(ctx context.Context) (int64, bool, error) {
	rendered, err := r.Render(ctx)
	if err != nil {
		return 0, false, err
	}
	sum := checksum(rendered)
	prev, err := r.Store.LatestChecksum(ctx)
	if err != nil {
		return 0, false, err
	}
	if prev == sum {
		b, err := r.Store.GetLatestBundle(ctx)
		if err != nil {
			return 0, false, nil
		}
		return b.Version, false, nil
	}
	version, err := r.Store.InsertConfigBundle(ctx, rendered, sum)
	if err != nil {
		return 0, false, err
	}
	// Best-effort poke; agents also long-poll so a missed publish self-heals.
	_ = r.Store.Redis.Publish(ctx, RedisChannel, fmt.Sprintf("%d", version)).Err()
	return version, true, nil
}

func checksum(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}
